CREATE TABLE IF NOT EXISTS financeiro_configuracoes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), escopo VARCHAR(20) NOT NULL, codigo_academia VARCHAR(50), ativo BOOLEAN NOT NULL DEFAULT false, motivo TEXT, alterado_por UUID, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version INTEGER NOT NULL DEFAULT 1, UNIQUE(escopo, codigo_academia)
);
CREATE TABLE IF NOT EXISTS financeiro_appypay_credenciais (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), contexto_tipo VARCHAR(20) NOT NULL CHECK (contexto_tipo IN ('spuri','academia')), codigo_academia VARCHAR(50), ambiente VARCHAR(10) NOT NULL CHECK (ambiente IN ('test','prod')), auth_base_url TEXT NOT NULL, api_base_url TEXT NOT NULL, webapi_base_url TEXT, client_id TEXT NOT NULL, client_secret_encrypted TEXT NOT NULL, resource TEXT NOT NULL, applications JSONB NOT NULL DEFAULT '[]', webhook_secret_encrypted TEXT, status VARCHAR(30) NOT NULL DEFAULT 'pendente_validacao', created_by UUID, updated_by UUID, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version INTEGER NOT NULL DEFAULT 1, CONSTRAINT cred_academia_ctx CHECK ((contexto_tipo='spuri' AND codigo_academia IS NULL) OR (contexto_tipo='academia' AND codigo_academia IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cred_spuri_amb ON financeiro_appypay_credenciais(ambiente) WHERE contexto_tipo='spuri';
CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cred_acad_amb ON financeiro_appypay_credenciais(codigo_academia, ambiente) WHERE contexto_tipo='academia';
CREATE TABLE IF NOT EXISTS financeiro_cobrancas (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), contexto_tipo VARCHAR(20) NOT NULL, codigo_academia VARCHAR(50), pagador_tipo VARCHAR(40) NOT NULL, pagador_id VARCHAR(80) NOT NULL, valor NUMERIC(14,2) NOT NULL, moeda VARCHAR(3) NOT NULL DEFAULT 'AOA', metodo_pagamento VARCHAR(20) NOT NULL, descricao TEXT NOT NULL, referencia_externa TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}', merchant_transaction_id TEXT NOT NULL, provider_charge_id TEXT, response_status TEXT, status VARCHAR(30) NOT NULL DEFAULT 'criada', raw_provider_response JSONB, created_by UUID, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, version INTEGER NOT NULL DEFAULT 1, UNIQUE(contexto_tipo, COALESCE(codigo_academia,''), referencia_externa), UNIQUE(merchant_transaction_id)
);
CREATE TABLE IF NOT EXISTS financeiro_transacoes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), cobranca_id UUID REFERENCES financeiro_cobrancas(id), tipo VARCHAR(40) NOT NULL, status_anterior VARCHAR(30), status_novo VARCHAR(30), response_status TEXT, payload JSONB NOT NULL DEFAULT '{}', autor UUID, motivo TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS financeiro_reembolsos (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), cobranca_id UUID REFERENCES financeiro_cobrancas(id), valor NUMERIC(14,2) NOT NULL, status VARCHAR(30) NOT NULL, provider_refund_id TEXT, motivo TEXT, created_by UUID, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS financeiro_reversoes (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), cobranca_id UUID REFERENCES financeiro_cobrancas(id), status VARCHAR(30) NOT NULL, provider_reverse_id TEXT, motivo TEXT, created_by UUID, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS financeiro_webhooks_recebidos (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), provider_event_id TEXT NOT NULL, contexto_tipo VARCHAR(20) NOT NULL, codigo_academia VARCHAR(50), payload JSONB NOT NULL, valido BOOLEAN NOT NULL, processado BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(contexto_tipo, COALESCE(codigo_academia,''), provider_event_id));
CREATE TABLE IF NOT EXISTS financeiro_reconciliacoes (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), contexto_tipo VARCHAR(20), codigo_academia VARCHAR(50), cobranca_id UUID, tipo VARCHAR(50) NOT NULL, detalhe JSONB NOT NULL DEFAULT '{}', status VARCHAR(30) NOT NULL DEFAULT 'detectada', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
